src/AppBundle/Entity/Event.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Event
 *
 * @ORM\Table(name="event")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\EventRepository")
 */
class Event
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime")
     */
    private $date;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="details", type="text", nullable=true)
     */
    private $details;


    /**
     * @var boolean
     *
     * @ORM\Column(name="completed", type="boolean", nullable=false, options={"default": false})
     */
    private $completed = false;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Event
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Event
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set details
     *
     * @param string $details
     *
     * @return Event
     */
    public function setDetails($details)
    {
        $this->details = $details;

        return $this;
    }

    /**
     * Get details
     *
     * @return string
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Get details
     *
     * @return string
     */
    public function getDetailsTrimmed()
    {
        return mb_strimwidth($this->details, 0, 100, '...');
    }

    /**
     * @return boolean
     */
    public function getCompleted(): bool
    {
        return $this->completed;
    }

    /**
     * @param boolean $completed
     */
    public function setCompleted(bool $completed): void
    {
        $this->completed = $completed;
    }

    public function isPastDue()
    {
        $now = new \DateTime();
        return $now > $this->getDate();
    }
}

src/AppBundle/Form/EventType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('completed', CheckboxType::class, [
                'required' => false,
            ])
            ->add('date', DateTimeType::class, [
                'required' => true,

                'widget' => 'single_text',
                'html5' => false,
                'format' => 'dd.MM.y HH:mm',

                'attr' => [
                    'class' => 'date-picker',
                ],
            ])
            ->add('title', TextType::class, [
                'required' => true,
            ])
            ->add('details', TextareaType::class, [
                'required' => false,
            ]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Event',
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_event';
    }


}

src/AppBundle/Resources/views/event/card.html.twig
{% extends 'headless.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-xs-12">
            <div class="card-body">
                <h4 class="card-title">{{ event.title }}</h4>
                <b class="card-title">{{ event.date|date("d M Y H:i") }}</b>
                <p class="card-text">
                    {{ event.details|nl2br }}
                </p>
            </div>

            <a class="btn btn-success" href="{{ url('event_complete', { 'id': event.id }) }}">Complete</a>
        </div>
    </div>
    <br>
{% endblock %}

src/AppBundle/Resources/views/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-sm-12 col-lg-8 offset-lg-2">
            <h3>Edit event </h3>

            {{ form_start(edit_form) }}
            {{ form_widget(edit_form) }}
            <input class="btn btn-success" type="submit" value="Save"/>
            <a class="btn btn-danger btn-delete" href="{{ url('event_delete', {'id': event.id}) }}">Delete</a>
            <a class="btn btn-info" href="{{ url('event_list') }}">Cancel</a>
            {{ form_end(edit_form) }}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/event/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col">
            <h3>Today's schedule</h3>
            {% if past %}

                <div class="card">
                    <div class="card-header">
                        <b>Past events</b>
                    </div>
                    <div class="card-body">
                        You have {{ past }} past event(s) for today
                        <br>
                        <a href="{{ url('event_list_past_today') }}">View all past for today</a>
                    </div>
                </div>
                <br>
            {% endif %}

            {% if current %}
                <div class="card">
                    <div class="card-header">
                        <b>Current Event</b>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">{{ current.title }}</h4>
                        <b class="card-title">{{ current.date|date("d M Y H:i") }}</b>
                        <p class="card-text">
                            {{ current.detailsTrimmed|nl2br }}
                        </p>

                        <a href="{{ url('event_card', { 'id': current.id }) }}" class="btn btn-primary btn-card">
                            View
                        </a>
                        <a href="{{ url('event_complete', { 'id': current.id }) }}" class="btn btn-success">
                            Complete
                        </a>
                    </div>
                </div>
            {% else %}
                <div class="alert alert-success">No upcoming events for today</div>
            {% endif %}

            {% if upcoming %}
                <br>
                <div class="card">
                    <div class="card-header">
                        <b>Upcoming event</b>
                    </div>
                    <div class="card-body">
                        You have {{ upcoming }} upcoming event(s)
                        <br>
                        <a href="{{ url('event_list_upcoming_today') }}">View all upcoming for today</a>
                    </div>
                </div>
                <br>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/event/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col">

            <h3>Events</h3>

            {% if events is empty %}
                <div class="alert alert-info">No records</div>
            {% else %}
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th class="{{ events.isSorted('e.date') ? 'sorted  : ' }}">
                            {{ knp_pagination_sortable(events, 'Birthday', 'e.date') }}
                        </th>
                        <th class="{{ events.isSorted('e.title') ? 'sorted' : '' }}" nowrap="true">
                            {{ knp_pagination_sortable(events, 'Title', 'e.title') }}
                        </th>
                        <th class="{{ events.isSorted('e.details') ? 'sorted' : '' }}" nowrap="true">
                            {{ knp_pagination_sortable(events, 'Details', 'e.details') }}
                        </th>
                        <th class="{{ events.isSorted('e.completed') ? 'sorted  : ' }}">
                            {{ knp_pagination_sortable(events, 'Status', 'e.completed') }}
                        </th>
                        <th>
                            Actions
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for event in events %}
                        <tr>
                            <td>
                                {{ event.date|date('d.m.Y H:i') }}
                            </td>
                            <td class="text-nowrap">
                                <a href="{{ url('event_show', { 'id': event.id }) }}">
                                    {{ event.title }}
                                </a>
                            </td>
                            <td class="">
                                {{ event.detailsTrimmed|nl2br }}
                            </td>
                            <td class="text-nowrap">
                                {% if event.completed %}
                                    <span><i class="fa fa-calendar-check"></i> Completed</span>
                                {% elseif event.isPastDue %}
                                    <span><i class="fa fa-history"></i> Past due</span>
                                {% else %}
                                    <span><i class="fa fa-clock"></i> Upcoming</span>
                                {% endif %}
                            </td>
                            <td class="text-nowrap">
                                <a class="btn btn-info" href="{{ url('event_show', { 'id': event.id }) }}">View</a>
                                <a class="btn btn-warning" href="{{ url('event_edit', { 'id': event.id }) }}">Edit</a>
                                <a class="btn btn-danger btn-delete" href="{{ url('event_delete', {'id': event.id}) }}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {{ knp_pagination_render(events) }}
            {% endif %}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/event/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-sm-12 col-lg-8 offset-lg-2">
            <h3>New event</h3>

            {{ form_start(form) }}
            {{ form_widget(form) }}
            <input class="btn btn-success" type="submit" value="Create"/>
            <a class="btn btn-info" href="{{ url('event_list') }}">Cancel</a>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/event/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <h3>Event</h3>

            <table class="table table-striped">
                <tbody>
                <tr>
                    <th>Date</th>
                    <td>
                        {{ event.date|date('d.m.Y H:i') }}
                    </td>
                </tr>
                <tr>
                    <th>Title</th>
                    <td>
                        {{ event.title }}
                    </td>
                </tr>
                <tr>
                    <th>Details</th>
                    <td>
                        {{ event.details|nl2br }}
                    </td>
                </tr>
                <tr>
                    <th>Status</th>
                    <td>
                        {% if event.completed %}
                            <span><i class="fa fa-calendar-check"></i> Completed</span>
                        {% elseif event.isPastDue %}
                            <span><i class="fa fa-history"></i> Past due</span>
                        {% else %}
                            <span><i class="fa fa-clock"></i> Upcoming</span>
                        {% endif %}
                    </td>
                </tr>
                </tbody>
            </table>

            <a class="btn btn-warning" href="{{ url('event_edit', { 'id': event.id }) }}">Edit</a>
            <a class="btn btn-danger btn-delete" href="{{ url('event_delete', {'id': event.id}) }}">Delete</a>
            <a class="btn btn-info" href="{{ url('event_list') }}">Back to the list</a>
        </div>
    </div>
{% endblock %}